import { useState } from 'react'
import LineChart from '../components/LineChart'
import type { FundamentalCatalog, FundamentalSnapshot } from '../types'

const colors = ['#ef8d5e', '#5cc8b0', '#bc7bea', '#e3b55e', '#8fa4c7', '#ee6f9c']

export default function FundamentalsPage({ catalog, snapshot }: { catalog: FundamentalCatalog; snapshot: FundamentalSnapshot }) {
  const tickers = snapshot.coverage.tickers
  const [ticker, setTicker] = useState(tickers[0] ?? '')
  const core = catalog.factors.filter((factor) => factor.priority === 'core')
  const groups = [...new Set(catalog.factors.map((factor) => factor.family))]
  const series = snapshot.series.filter((item) => item.ticker === ticker)
  const opSeries = series.find((item) => item.metric === 'standardized_operating_profit')
  return <main className="page"><a className="back" href={import.meta.env.BASE_URL}>← 因子总览</a><section className="detail-head"><p className="eyebrow">FUNDAMENTAL STATES / 04</p><h1>经营状态，<em>慢慢变成信号。</em></h1><p className="lede">把财报中的盈利、估值、财务质量和资产风险，整理成一张可审计的研究地图。</p><span className="badge">PIT VINTAGE · {snapshot.vintage}</span></section><section className="metrics"><div className="metric-card"><span>PIT 观察区间</span><strong>{snapshot.coverage.date_start} → {snapshot.coverage.date_end}</strong><small>{snapshot.dataset}</small></div><div className="metric-card"><span>代表股票</span><strong>{snapshot.coverage.tickers.length}</strong><small>{snapshot.coverage.tickers.join(' · ')}</small></div><div className="metric-card"><span>目录因子</span><strong>{catalog.factors.length}</strong><small>6 core · 12 supporting</small></div><div className="metric-card"><span>数据行</span><strong>{snapshot.coverage.observations.toLocaleString()}</strong><small>已聚合 PIT 观察</small></div></section><section className="section"><div className="section-heading"><p className="eyebrow">CORE RESEARCH SET</p><h2>先看这六个</h2></div><div className="core-grid">{core.map((factor, index) => <div className="factor-tile" key={factor.id}><span className="tile-dot" style={{ background: colors[index] }} /><p>{factor.family}</p><h3>{factor.name}</h3><code>{factor.formula}</code><small>{factor.meaning}</small></div>)}</div></section><section className="section"><div className="section-heading"><p className="eyebrow">FACTOR CATALOG</p><h2>18 个研究入口</h2></div><div className="catalog-grid">{groups.map((group) => <div className="catalog-group" key={group}><h3>{group}</h3>{catalog.factors.filter((factor) => factor.family === group).map((factor) => <div className="catalog-row" key={factor.id}><span>{factor.name}</span><code>{factor.formula}</code></div>)}</div>)}</div></section><section className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">LOCAL PIT SNAPSHOT</p><h2>标准化营业利润试算</h2></div><select value={ticker} onChange={(event) => setTicker(event.target.value)}>{tickers.map((item) => <option key={item}>{item}</option>)}</select></div>{opSeries ? <LineChart dates={opSeries.dates} series={[{ name: 'Z(OP_TTM)', values: opSeries.values, color: '#ef8d5e' }]} /> : <div className="chart-empty">前 6 个历史 TTM 不足，暂无可计算的标准化值</div>}<p className="annotation">数据来自本地 A 股 PIT vintage；标准化营业利润只在四个完整季度加上六个历史 TTM 都可用时显示，否则保留 null。</p></section><section className="panel warning-panel"><p className="eyebrow">RESEARCH GUARDRAILS</p><h2>这页有意保守</h2><ul>{catalog.research_notes.slice(1).map((note) => <li key={note}>{note}</li>)}</ul><p>当前页面展示的是研究数据接入与公式验证，不包含 IC、分层收益或交易建议。</p></section></main>
}
