import MetricCard from '../components/MetricCard'
import type { FactorRecord, ResearchContext, Snapshot } from '../types'

export default function OverviewPage({ snapshot, records, context }: { snapshot: Snapshot; records: FactorRecord[]; context: ResearchContext }) {
  const dataset = snapshot.datasets[0]
  const minuteCount = records.filter((record) => record.family !== 'Hermite 元因子' && record.frequencyIn === 'minute').length
  const hermiteCount = records.filter((record) => record.family === 'Hermite 元因子').length
  const fundamentalCount = records.filter((record) => record.frequencyIn === 'PIT quarterly reports').length
  const experimentalCount = records.filter((record) => record.status === 'experimental').length
  return <main className="page"><section className="hero"><p className="eyebrow">RESEARCH NOTEBOOK / 01</p><h1>把市场数据，<em>变成可读的结构。</em></h1><p className="lede">探索分钟波动、跳跃、Hermite 状态，以及财报中的盈利变化如何共同构成因子研究地图。</p><span className="badge">{snapshot.source === 'demo' ? 'DEMO SNAPSHOT' : 'PARQUET SNAPSHOT'}</span></section><section className="context-strip"><span><strong>数据</strong>{context.source}</span><span><strong>范围</strong>{context.snapshotRange}</span><span><strong>股票池</strong>{context.universe}</span><span><strong>频率</strong>{context.frequency}</span><span><strong>PIT</strong>{context.pitStatus}</span></section><section className="metrics"><MetricCard label="交易日" value={dataset?.trading_days.toLocaleString() ?? '—'} note={`${dataset?.date_start} → ${dataset?.date_end}`} /><MetricCard label="覆盖股票" value={dataset?.tickers.toLocaleString() ?? '—'} note="A 股横截面" /><MetricCard label="因子总数" value={records.length.toLocaleString()} note={`${records.filter((record) => record.family !== 'Hermite 元因子' && record.frequencyIn === 'minute').length} 分钟 + ${hermiteCount} Hermite + ${fundamentalCount} 基本面`} /><MetricCard label="实验性" value={experimentalCount.toLocaleString()} note="尚未完成预测性验证" /></section><section className="section"><div className="section-heading"><p className="eyebrow">FACTOR ATLAS</p><div className="section-heading-row"><h2>因子地图</h2><a className="section-link" href={`${import.meta.env.BASE_URL}factors`}>浏览全部因子 →</a></div></div><div className="group-grid">{snapshot.factor_groups.map((group, index) => <a className="group-card" href={`${import.meta.env.BASE_URL}${index === 0 ? 'factors/realized_variance' : 'hermite'}`} key={group.name}><span className="group-index">0{index + 1}</span><div><h3>{group.label}</h3><p>{group.name}</p></div><strong>{index === 0 ? minuteCount : hermiteCount}</strong></a>)}<a className="group-card" href={`${import.meta.env.BASE_URL}fundamentals`}><span className="group-index">03</span><div><h3>基本面经营状态</h3><p>fundamental factor catalog</p></div><strong>{fundamentalCount}</strong></a></div></section><section className="section flow"><div className="section-heading"><p className="eyebrow">THE PIPELINE</p><h2>从原始数据到体制信号</h2></div><div className="flow-row"><span>分钟 OHLCV</span><i>→</i><span>波动 / 流动性</span><i>→</i><span>跳跃分解</span><i>→</i><span>Hermite 元因子</span><i>→</i><span>财报 PIT</span><i>→</i><span>ML / 回测</span></div></section></main>
}
